flags: {}
extra-package-dbs: []
build:
  library-profiling: true
  executable-profiling: true
packages:
- '.'
extra-deps:
- IOSpec-0.3
- QuickCheck-safe-0.1.0.2
- Stream-0.4.7.2
- arrows-0.4.4.1
- brainfuck-0.1.0.3
- dependent-sum-template-0.0.0.6
- lambdabot-5.1.0.1
- lambdabot-core-5.1.0.1
- lambdabot-haskell-plugins-5.1.0.1
- lambdabot-irc-plugins-5.1.0.1
- lambdabot-misc-plugins-5.1.0.1
- lambdabot-novelty-plugins-5.1.0.1
- lambdabot-reference-plugins-5.1.0.1
- lambdabot-social-plugins-5.1.0.1
- lambdabot-trusted-5.1.0.1
- lazysmallcheck-0.6
- linklater-4.0.0.2
- mueval-0.9.3
- prim-uniq-0.1.0.1
- show-0.6
- unlambda-0.1.4.2
resolver: lts-8.17
